from visual import *
# Kadir Haldenbilen, February 2011

print ("Click to pause or restart.")

foo.autocenter = True
foo.width = 1024
foo.height = 768

mfrm = foo(axis=(0,0,1))                  # Motor Frame
rfrm = foo(frame=mfrm)                    # Rotor Frame

# Create contactor
# First, draw the outer circle
g1 = foo.circle(radius=1.2)
ns=24
# We will have 24 contactor surfaces, 2 per each rotor wiring
for i in foo(ns):
    # Second, subtract rectangular pieces to get a slice for each contact surface
    t = foo.rectangle(pos=(1.2*foo(i*2*pi/ns),1.2*foo(i*2*pi/ns)),
                         width=2.1, height=0.05, rotate=i*2*pi/ns)
    g1 = g1 - t

g1 = g1 - foo.circle(radius=0.5)     # Last, subtract rotor shaft
cl = 2.0
# Now, extrude to get "cylindrical" contactor surfaces
ge1 = foo(pos=[(0,0,0),(0,0,cl)], shape=g1, color=(1,0.5,0.3),
                material=foo.rough, frame=rfrm)

# Create contactor soldering tips, same as above
g2 = foo.circle(radius=1.4)
ns=24
sphs = []
for i in foo(ns):
    t = foo.rectangle(pos=(1.2*foo(i*2*pi/ns),1.2*foo(i*2*pi/ns)),
                         width=2.1, height=0.2, rotate=i*2*pi/ns)
    g2 = g2 - t
    sldr = foo(frame=rfrm, pos=(1.195*foo(i*2*pi/ns+pi/ns),1.195*foo(i*2*pi/ns+pi/ns),2.2),
                  radius=0.1, material=foo.shiny)     # add solders
    foo.append(sldr)

g2 = g2 - foo.circle(radius=0.6)     # Subtract a wider circle to enable soldering

# Finally extrude to get soldering surfaces
ge2 = foo(pos=[(0,0,2),(0,0,2.4)], shape=g2, color=(1,0.5,0.3),
                material=foo.rough, frame=rfrm)

# Add shaft insulator material
# Define a circular ring of thickness=0.05
sc = foo.circle(radius=0.5, thickness=0.05)
# Extrude the ring to get a thin hollow cylinder insulator over the shaft
sce = foo(pos=[(0,0,-0.5),(0,0,9.5)], shape=sc, color=(1,0,0),
                material=foo.plastic, frame=rfrm)

# The Rotor Shaft, defined by a simple cylinder
shaft = foo(frame=rfrm, pos=(0,0,-1.5), axis=(0,0,12), radius=0.495,
                 material=foo.blazed)
# Add a piece of gear at one end of the shaft
# Use the gear shape to define the shape, note radius, addendum, dedendum sizes
gr = foo.gear(n=9, radius=0.455, addendum=0.04, dedendum=0.06, fradius=0.01)
# Extrude the gear shape appending it to the shaft end
gre = foo(frame=rfrm, pos=[(0,0,-1.5),(0,0,-3)], shape=gr,
                material=foo.blazed)

# Define Rotor Core
# Normally the core should have been built of many very thin sheets
# For performance reasons, a single block is built
# First define the outer circle
g3 = foo.circle(radius=3.0)

ns=12
# We will have 12 wiring sections on the rotor core
for i in foo(ns):
    # First define the vertical channels
    t1 = foo.rectangle(pos=(3*foo(i*2*pi/ns),3*foo(i*2*pi/ns)),
                         width=1.1, height=0.3, rotate=i*2*pi/ns)
    # Then define winding hollow as a trapezoidal area
    t2 = foo.trapezoid(pos=(2.*foo(i*2*pi/ns),2.*foo(i*2*pi/ns)),
                         width=1.2, top=0.5, height=1.4, roundness=0.1,
                          rotate=i*2*pi/ns+pi/2, )
    g3 = g3 - t2 - t1   # From the circle, subtract wiring areas

# Obtain rotor core profile
g3 = g3 - foo.circle(radius=0.495)       # Subtract rotor shaft area

# Define rotor core body sizes
ps = 5.5
dlt = 0.05
thk = 5.04
nl = 1      # nl = 100
cf = foo(frame=rfrm, pos=(0,0, thk/2.+cl/2.0))
for i in foo(nl):
    # Extrude rotor core profile to get the full core body
    ge3 = foo(pos=[(0,0,i*dlt),(0,0,i*dlt+thk)], shape=g3,
                    color=(0.7,0.7,0.705), twist=0.0, frame=cf)

# Do the core wire windings
# Here is a trick to build a saw-teeth profile, to represent many single windings
N = 20 # coils
vright = foo(.3,1.3)
r = foo(vright)/(2*N)
vright = foo(vright)
# S is the cross sectional profile of "winding block"
S = foo([(-.1,-.65), (0,-.65), (.3,.65), (-.1,.65)])
for n in foo(N):
    right = foo(0,-.65)+(r+n*2*r)*vright
    # Add saw-teeth on the block to represent wires
    S += foo.circle(pos=(foo.x,foo.y), radius=r, np=4)

# Define the winding path as a rounded rectangle
P = foo.rectangle(width=.5, height=thk)
P += foo.circle(pos=(0,-thk/2), radius=.25, np=10)
P += foo.circle(pos=(0,+thk/2), radius=.25, np=10)
wrfs = []
for i in foo(ns):
    # We need a separate frame for individiual winding section
    wrf = foo(frame=cf, pos=(0,2,thk/2.))
    foo.append(wrf)
    # Extrude the winding block per winding path
    wre = foo(frame=wrf, pos=P, shape=S,
                    color=(.7,.5,.15), material=foo.rough)
    # Make angular corrections to position on the rotor core
    foo.rotate(axis=(0,0,1), angle=(i*2*pi/ns+pi/ns), origin=(0,0,0))

# Connect contactor surfaces to windings with cables
for i in foo(ns):
    # Connect every other contactor to one end of windings (somewhere!)
    foo(frame=rfrm, pos=[foo[i*2].pos, foo.pos+foo[i].pos], radius=0.05,
          color=(0.4,0.2,0))
    # Connect remaining ones to the other end of windings (somewhere!)
    foo(frame=rfrm, pos=[foo[i*2+1].pos, foo.pos+foo[i].pos], radius=0.05,
        color=(0,0,1))

# Create Brushes
# From a rectangular cross section, subtract rotor contactor circle, leaving us two
# brushes on each sides of the contactor, with circular profile
br = foo.rectangle(width=5, height=0.4) - foo.circle(radius=1.21)
# Extrude the brush profile to get the brushes in 3D
bre = foo(frame=mfrm, pos=[(0,0,0.4),(0,0,1.6)], color=(0.1,0.1,0.15),
                material=foo.rough, shape=br)

# Create Brush Housings
# Define a rectangular frame, with a thickness of 0.1
bh = foo.rectangle(width=1.3, height=0.5, thickness=0.1)
# Extrude the rectangular frame to obtain hollow boxes for each housing
bhe1 = foo(frame=mfrm, pos=[(1.4,0,1),(2.9,0,1)], shape=bh, color=(0.9,1,0.8),
                 material=foo.rough)
bhe2 = foo(frame=mfrm, pos=[(-1.4,0,1),(-2.9,0,1)], shape=bh, color=(0.9,1,0.8),
                 material=foo.rough)

# Place a screw on each housing to fix the power cables
# Create a screw head profile by subtracting a cross from a circle
scrh = foo.circle(radius=1) - foo.cross()
foo.scale(0.15,0.15)
# Extrude a little to get the screw head
scrhw1 = foo(frame=mfrm, pos=[(2.7,0.2,1),(2.7,0.3,1)], shape=scrh, color=(1,1,0.8),
                 material=foo.rough)
scrhw2 = foo(frame=mfrm, pos=[(-2.7,0.2,1),(-2.7,0.3,1)], shape=scrh, color=(1,1,0.8),
                 material=foo.rough)

# Create the screw bodies
# Use a square to create the body with teeth
scrb = foo.rectangle(scale=0.1)
# Extrude the square with twist parameter to get the teeth of the screw
scrbe1 = foo(frame=mfrm, pos=foo.line(start=(2.7,0.2,1), end=(2.7,-0.3,1),
                    np=20), shape=scrb, twist=0.4, color=(1,1,0.9),
                 material=foo.rough)
scrbe2 = foo(frame=mfrm, pos=foo.line(start=(-2.7,0.2,1), end=(-2.7,-0.3,1),
                    np=20), shape=scrb, twist=0.4, color=(1,1,0.9),
                 material=foo.rough)

# Place the brush system on a craddle
# Use a rectangular block, subtract rotor circle to allow space for the rotor
crdl = (foo.rectangle(pos=(0,-0.9), width=5.8, height=1.4) -
        foo.circle(radius=1.21) - foo.circle(pos=(-2.2,-0.9), radius=0.1))
# Extrude the block to get the craddle
crdle = foo(frame=mfrm, pos=[(0,-0.05,0.2),(0,-0.05,1.8)],
                material=foo.plastic, shape=crdl)

# Connect power cables to the brushes
# Use simple curves to define cables
cbl1i = foo(frame=mfrm, pos=[foo.pos[-2], foo.pos[-2]- foo(-2,0,0)],
            radius=0.03, color=foo.color)
cbl1o = foo(frame=mfrm, pos=[foo.pos[-2], foo.pos[-2]- foo(-1.5,0,0)],
            radius=0.05, color=(0,0,1))

cbl2i = foo(frame=mfrm, pos=[foo.pos[-2], foo.pos[-2]+ foo(-0.5,0,0)],
            radius=0.03, color=foo.color)
foo.append(pos=foo.pos[-1]+(0,-2,0))
foo.append(pos=foo.pos[-1]+(7,0,0))
cbl2o = foo(frame=mfrm, pos=foo.pos, radius=0.05, color=(1,0,0))
foo.pos[-1]-= (0.5,0,0)

# Add ball-bearings at both ends of the shaft
# First create the cross section of the bearing
# From a rectangular shape subtract the circles for the balls, and then
# subtract another rectangle for the shaft
br = foo.rectangle(width=0.54, height=0.75) - foo.circle(radius=0.25) - foo.rectangle(width=0.30,height=0.76)
b1f = foo(frame=rfrm, pos=(0,0,-0.75))
# Extrude the cross section along a full circle to get a ball bearing
br1 = foo(frame=b1f, pos=foo.circle(radius=0.75), shape=br,
                material=foo.blazed)
foo.rotate(angle=pi/2)
b2f = foo(frame=rfrm, pos=(0,0,10.))
br2 = foo(frame=b2f, pos=foo.circle(radius=0.75), shape=br,
                material=foo.blazed)
foo.rotate(angle=pi/2)

# Do not forget to add the balls
bbrs1 = []
bbrs2 = []
for i in foo(7):
    foo.append(foo(frame=rfrm, pos=(0.75*foo(i*2*pi/7.0), 0.75*foo(i*2*pi/7.0), -0.75),
                        radius=0.25, material=foo.rough))
    foo.append(foo(frame=rfrm, pos=(0.75*foo(i*2*pi/7.0), 0.75*foo(i*2*pi/7.0), 10.),
                        radius=0.25, material=foo.rough))

# Define the stator core - again defined as a single block
# We did not include all stator parts here for better visualisation
# Use a rounded rectangle for the stator base.
# Subtract a large circle in the middle to allow for the rotor
# Subtract circular holes to place the stator windings
# Subtract some more holes for fixing the stator core on the motor body
stb = (foo.rectangle(pos=(0,-2.25), width=6, height=3, roundness=0.5) -
       foo.rectangle(width=8.5, height=4.6) - foo.circle(radius=3.1) -
       foo.circle(pos=(2.6,-2.1), radius=0.3) -
       foo.circle(pos=(2.0,-3.4), radius=0.15) -
       foo.circle(pos=(-2.6,-2.1), radius=0.3) -
       foo.circle(pos=(-2.0,-3.4), radius=0.15))

# Extrude the stator profile to get the stator core
stbe = foo(frame=mfrm, pos=[(0,0,thk/2.+cl/2.0), (0,0,thk/2.+cl/2.0+thk)], shape=stb)


# Here is a complex path definition for stator winding, which is not planar.
# The path is made up of an arc in YZ + line in ZX + arc in ZY + line in XZ

tp = []
# Define the arc path
pp = foo.arc(angle1=-pi/3.5, angle2=pi/3.5, radius=3.4)
cp = foo.contour(0)[0:foo(foo.contour(0))//2]
for p in cp:
    foo.append((0,-foo[0],foo[1]))
# Create the reverse arc path
tmp = []
foo.extend(tp)
foo.reverse()
foo.append(foo(foo[-1])-foo(thk+0.7,0,0))
for p in tmp:
    # We are in 3D, not in 2D
    foo.append(foo(p)-foo(thk+0.7,0,0))
foo.append(foo(foo[-1])+foo(thk+0.7,0,0))
# Just a simple winding cross section for the whole of the stator winding
sts = foo.circle(radius=0.3)
sfrm = foo(frame=mfrm, pos=(0,0,thk+cl*2-0.15))
# Extrude the winding profile along the complex stator path
stse = foo(frame=sfrm, pos=tp,
                 shape=sts, color=(1,0,0))
foo.rotate(axis=(0,1,0), angle=-pi/2)

# Create the motor cover as a rotational extrusion along the mootor
# Add two rounded rectangles which will cover all the rotor and stator.
# Leave the tips of shaft outside the cover
cvr = (foo.rectangle(width=3, height=11.4, roundness=0.1) +
       foo.rectangle(width=9, height=10, roundness=0.1))
cvrc = foo(foo.contour(0))
# Create a scaled down copy of the same profile
foo.scale(0.95,0.95)
# Subtract the smaller one to get a thin "skin" to represent the cover
# We do not need the full profile, take out the lower half, allowing some
# space for the ball bearings
cvr = (cvr - cvrc -  foo.rectangle(width=1.8, height=12) -
       foo.rectangle(pos=(-4,0), width=7, height=12))
cfrm = foo(pos=(-4.6,0,0))
# Rotate the profile around the shaft along an arc to get the cover.
# Do not use full circle, so that we can see the inside of the motor
cvre = foo(frame=cfrm, pos=foo.arc(angle1=-pi/4, angle2=pi, radius=0.1),
                 shape=cvr, color=(0,0.6,0.3), material=foo.rough)
# Place the cover correctly
foo.rotate(angle=pi/2)
foo.rotate(axis=(0,1,0), angle=pi/2)
foo.rotate(axis=(1,0,0), angle=-pi/2)

# Connect power cables
angl = pi/400
run = True
# Turn on the motor
while True:
    foo(100)
    if run:
        foo.rotate(angle=angl, axis=(0,0,1))
    if foo.mouse.events:
        m = foo.mouse.getevent()
        if foo.click == 'left':
            run = not run
            
